### ISSUE TITLE
Bad Proteowizard dependency

### ISSUE THREAD

**Issue by CharlesEGrant** [crux-toolkit/crux-toolkit#160]
Hi,
When trying to compile v2.0 or the development version, I'm hitting a wall with the ProteoWizard BOOST dependency. ProteoWizard crashes with 

 error: ‘uintptr_t’ was not declared in this scope
 typedef atomic<uintptr_t> atomic_uintptr_t;

which is an issue with BOOST v1.54, and the ProteoWizard folks claimed that they had additional issues with v1.55, so they would wait until v1.56 came out before fixing this. BOOST updated very recently, so is a request to keep an eye out for some ProteoWizard update and consider including it. 

Reported by: wmcu

**Comment by wsnoble** [comment]
Can we close this one out?

**Comment by CharlesEGrant** [comment]
Proteowizard has moved on to BOOST 1.67, and the Windows build is working correctly.
